### ISSUE TITLE
Sentence in Example 3.1 "Here is Why" ends prematurely

### ISSUE THREAD

**Issue by jaf7** [rasbt/python_reference#18]
Thanks for this very helpful intro.  Hope this isn't just an annoying nitpick.  The sentence:

*"As we go up in Python's L -> E -> G -> B hierarchy, the function a_func() finds len() already in the global scope first before it attempts"*

is missing an ending such as "to search the Built-in namespace."
I was referred to your tutorial by [MITx 6.00.1x Intro to CS & Programming Using Python] (https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-6)

**Comment by rasbt** [comment]
Thanks for the note; indeed, something got cut off there. It should be fixed now.
