### ISSUE TITLE
Broken link in SQLite3_howto README

### ISSUE THREAD

**Issue by rgeirhos** [rasbt/python_reference#24]
In the following README:
https://github.com/rasbt/python_reference/tree/master/tutorials/sqlite3_howto
the link in the line "Download the script: create_new_db.py" appears to be broken, it refers to https://raw.githubusercontent.com/rasbt/python_reference/master/tutorials/code/create_new_db.py which no longer exists.

The link URL should probably be replaced by
https://github.com/rasbt/python_reference/blob/master/tutorials/sqlite3_howto/code/create_new_db.py

**Comment by rasbt** [comment]
Thanks for the note! There were quite a couple of broken links like the one you mentioned. This probably happened when I created a subdirectory for this doc. I replaced everything with relative links now so that this shouldn't happen again in case I move something again in future.

Thanks!
