### ISSUE TITLE
Printing database summary

### ISSUE THREAD

**Issue by jvansan** [rasbt/python_reference#25]
I realize this post is fairly old, however I was wondering if you could please clarify.

It seems to me that in the functions you define in this section, you use the variable `c` for cursor within the function even though you pass the `cursor` object to the functions. 

Could you please address this?

**Comment by rasbt** [comment]
Thanks for the note! It was probably an oversight, and I am happy to fix this. In which particular file did you find this?

**Comment by rasbt** [comment]
Thanks! Should be fixed now!
